### ISSUE TITLE
Error: Cannot invoke a non-'const' constructor where a const expression is expected.

### ISSUE THREAD

**Issue by therasuldev** [MarsadMaqsood/stylish_bottom_bar#13]
: Error: Cannot invoke a non-'const' constructor where a const expression is expected.
bottom_bar.dart:421
Try using a constructor or factory that is 'const'.
            ? const Flex(
                    ^^^^
Target kernel_snapshot failed: Exception
2

FAILURE: Build failed with an exception.

**Comment by MarsadMaqsood** [comment]
can you share the relevant code to reproduce this error?

**Comment by ilkerx** [comment]
The same issue for me, just pasted the example code and it gave the same error. This is the exact text of the error:

/C:/Users/....../AppData/Local/Pub/Cache/hosted/pub.dev/stylish_bottom_bar-1.0.3/lib/src/bottom_bar.dart:421:21: Error: Cannot invoke a non-'const' constructor where a const expression is expected.
Try using a constructor or factory that is 'const'.
            ? const Flex(
                    ^^^^

**Comment by ThisIsMonta** [comment]
I've made a pull request with a solved version, @MarsadMaqsood can you merge that ? just to pass into the production version

**Comment by asergenalkan** [comment]
Hi there! Same issue with me.
When I try to build iOS app I'm facing with this issue. It's started to happen after lastest Xcode and cocoapods updates etc.
Here is log;

../../../../../.pub-cache/hosted/pub.dev/stylish_bottom_bar-1.0.3/lib/src/bottom_bar.dart:421:21: Error: Cannot invoke a non-'const' constructor where a const expression is expected.

How can I fix this ?
