### ISSUE TITLE
barStyle doesn't seem to work

### ISSUE THREAD

**Issue by RickBoyerDev** [MarsadMaqsood/stylish_bottom_bar#3]
Using your code from the Example, I just uncommented out the following lines:

  //Bubble bar specific style properties
  unselectedIconColor: Colors.grey,
  barStyle: BubbleBarStyle.horizotnal,
  bubbleFillStyle: BubbleFillStyle.fill,

I don't get the horizontal style.  I can change the animation and icon styles, but I can't get the horizontal option to work.  Am I missing something?

**Comment by MarsadMaqsood** [comment]
To use bubble style you need to use `BubbleBarItem` model in `items: []`

```dart

bottomNavigationBar: StylishBottomBar(
        items: [
          BubbleBarItem(icon: const Icon(Icons.abc), title: const Text('Abc')),
          BubbleBarItem(
              icon: const Icon(Icons.safety_divider),
              title: const Text('Safety')),
          BubbleBarItem(
              icon: const Icon(Icons.cabin), title: const Text('Cabin')),
        ],
        barStyle: BubbleBarStyle.horizotnal,
        iconSize: 32,
        opacity: 0.3,
        currentIndex: selected ?? 0,
        onTap: (index) {
          setState(() {
            selected = index;
          });
        },
      ),

```
