### ISSUE TITLE
Floating button overlape

### ISSUE THREAD

**Issue by hmaxhmax** [MarsadMaqsood/stylish_bottom_bar#4]
Nice work!
But floating button overlapping when keyboard is showing
see the screenshot 

![Screenshot 2022-07-12 160620](https://user-images.githubusercontent.com/52915626/178509489-e1a2e5f2-bfca-487e-b243-d7c3fcbf6a4f.jpg)

**Comment by MarsadMaqsood** [comment]
In your Scaffold, set the `resizeToAvoidBottomInset` property to `false`, to avoid this behavior, 

```dart

return Scaffold(
     resizeToAvoidBottomInset: false,
     
     body: ...
    
);

```

**Comment by hmaxhmax** [comment]
Thanks, it's working now
