### ISSUE TITLE
Hover background is out of bounds

### ISSUE THREAD

**Issue by monkeyWie** [MarsadMaqsood/stylish_bottom_bar#5]
Hi, I found a issue that running in windows, hover backgroud is out of bounds:

![image](https://user-images.githubusercontent.com/13160176/186871476-9564b236-3643-44d4-b2ae-03e2d33ff077.png)

Do you have any suggestions for this? Thank you~

**Comment by MarsadMaqsood** [comment]
@monkeyWie Thank You for pointing out this issue. 
Update the package version to see changes.

### Before

![before_fix](https://user-images.githubusercontent.com/53562046/187013844-cc8293ff-6feb-49c6-aaa7-2532b9802380.jpg)

### After

![after_fix](https://user-images.githubusercontent.com/53562046/187013853-bd2f8138-52b7-400c-9f8b-24642eec738d.jpg)

**Comment by monkeyWie** [comment]
@MarsadMaqsood I updated the version to 0.1.5, but it also doesn't seem to work.
![image](https://user-images.githubusercontent.com/13160176/187017428-c38740e1-5797-4ce9-bef3-0b7e4f30be71.png)

**Comment by MarsadMaqsood** [comment]
@monkeyWie can you share your bottom bar code to reproduce this hover behavior?

---
I checked and didn't find any suspicious hover behavior.

https://user-images.githubusercontent.com/53562046/187045219-1aa1f661-aa06-4e09-8941-ade4a3cdffd1.mov

**Comment by monkeyWie** [comment]
Oh, i didn't see it clearly, it no problem!
