### ISSUE TITLE
Flutter 3.7 compatibility

### ISSUE THREAD

**Issue by Navil** [MarsadMaqsood/stylish_bottom_bar#8]
With Flutter 3.7, this library broke.

The "Badge" class used by this library no clashes with the newly introduced Badge Widget from Material. 

`Error: 'Badge' is imported from both 'package:flutter/src/material/badge.dart' and 'package:stylish_bottom_bar/src/badge/badge.dart'.`

**Comment by MarsadMaqsood** [comment]
https://github.com/MarsadMaqsood/stylish_bottom_bar/pull/7#issue-1556412560
